// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attributes/attributes.proto

package attributes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttributesContext struct {
	Headers              map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sni                  string            `protobuf:"bytes,2,opt,name=sni,proto3" json:"sni,omitempty"`
	Port                 uint32            `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Tls                  bool              `protobuf:"varint,4,opt,name=tls,proto3" json:"tls,omitempty"`
	Clusters             []string          `protobuf:"bytes,5,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Weighet              []int32           `protobuf:"varint,6,rep,packed,name=weighet,proto3" json:"weighet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AttributesContext) Reset()         { *m = AttributesContext{} }
func (m *AttributesContext) String() string { return proto.CompactTextString(m) }
func (*AttributesContext) ProtoMessage()    {}
func (*AttributesContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8be56f51e48bb4, []int{0}
}

func (m *AttributesContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributesContext.Unmarshal(m, b)
}
func (m *AttributesContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributesContext.Marshal(b, m, deterministic)
}
func (m *AttributesContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributesContext.Merge(m, src)
}
func (m *AttributesContext) XXX_Size() int {
	return xxx_messageInfo_AttributesContext.Size(m)
}
func (m *AttributesContext) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributesContext.DiscardUnknown(m)
}

var xxx_messageInfo_AttributesContext proto.InternalMessageInfo

func (m *AttributesContext) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *AttributesContext) GetSni() string {
	if m != nil {
		return m.Sni
	}
	return ""
}

func (m *AttributesContext) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AttributesContext) GetTls() bool {
	if m != nil {
		return m.Tls
	}
	return false
}

func (m *AttributesContext) GetClusters() []string {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *AttributesContext) GetWeighet() []int32 {
	if m != nil {
		return m.Weighet
	}
	return nil
}

func init() {
	proto.RegisterType((*AttributesContext)(nil), "attributes.AttributesContext")
	proto.RegisterMapType((map[string]string)(nil), "attributes.AttributesContext.HeadersEntry")
}

func init() { proto.RegisterFile("attributes/attributes.proto", fileDescriptor_0e8be56f51e48bb4) }

var fileDescriptor_0e8be56f51e48bb4 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xb3, 0xdd, 0x8f, 0x51, 0x41, 0x07, 0x0f, 0x61, 0xbd, 0x04, 0x4f, 0xc1, 0x43,
	0x05, 0xbd, 0xc8, 0xde, 0x44, 0x05, 0xcf, 0xf9, 0x07, 0x5d, 0x1d, 0xdc, 0xb2, 0xa5, 0x29, 0xc9,
	0x54, 0xed, 0xd9, 0x3f, 0x2e, 0x69, 0xed, 0x07, 0x78, 0x7b, 0x9e, 0xf0, 0x66, 0xe6, 0x65, 0xe0,
	0x2a, 0x67, 0xf6, 0xc5, 0xbe, 0x61, 0x0a, 0xb7, 0x13, 0x66, 0xb5, 0x77, 0xec, 0x10, 0xa6, 0x97,
	0xeb, 0x9f, 0x04, 0x2e, 0x1e, 0x47, 0x7d, 0x72, 0x15, 0xd3, 0x37, 0xe3, 0x33, 0xac, 0x0e, 0x94,
	0xbf, 0x93, 0x0f, 0x4a, 0x68, 0x69, 0x4e, 0xee, 0x6e, 0xb2, 0xd9, 0x94, 0x7f, 0xf9, 0xec, 0xb5,
	0x0f, 0xbf, 0x54, 0xec, 0x5b, 0x3b, 0x7c, 0xc5, 0x73, 0x90, 0xa1, 0x2a, 0x54, 0xa2, 0x85, 0xd9,
	0xd8, 0x88, 0x88, 0xb0, 0xa8, 0x9d, 0x67, 0x25, 0xb5, 0x30, 0x67, 0xb6, 0xe3, 0x98, 0xe2, 0x32,
	0xa8, 0x85, 0x16, 0x66, 0x6d, 0x23, 0xe2, 0x16, 0xd6, 0x6f, 0x65, 0x13, 0x38, 0xae, 0x4f, 0xb5,
	0x34, 0x1b, 0x3b, 0x3a, 0x2a, 0x58, 0x7d, 0x51, 0xf1, 0x71, 0x20, 0x56, 0x4b, 0x2d, 0x4d, 0x6a,
	0x07, 0xdd, 0xee, 0xe0, 0x74, 0x5e, 0x23, 0xce, 0x3d, 0x52, 0xab, 0x44, 0xbf, 0xfd, 0x48, 0x2d,
	0x5e, 0x42, 0xfa, 0x99, 0x97, 0x0d, 0xfd, 0x35, 0xea, 0x65, 0x97, 0x3c, 0x88, 0xfd, 0xb2, 0x3b,
	0xcc, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x08, 0x71, 0x12, 0x37, 0x01, 0x00, 0x00,
}
